version: "3.8"

services:
  chat-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: chat-app
    ports:
      - "8080:5000"
    environment:
      - NODE_ENV=production
      # - VITE_HOST=0.0.0.0
      # - VITE_PORT=5000
    restart: always
